/**
 * Binary route data parser
 *
 * Parses route_data.bin files generated by preprocessor (v8 format).
 * Binary format must match Rust RouteData struct in shared/src/binfile.rs.
 *
 * RouteNode layout (#[repr(C, packed)], 52 bytes):
 * offset  0: len2_cm2     i64   8 bytes
 * offset  8: line_c       i64   8 bytes
 * offset 16: heading_cdeg i16   2 bytes
 * offset 18: _pad         i16   2 bytes
 * offset 20: x_cm         i32   4 bytes
 * offset 24: y_cm         i32   4 bytes
 * offset 28: cum_dist_cm  i32   4 bytes
 * offset 32: dx_cm        i32   4 bytes
 * offset 36: dy_cm        i32   4 bytes
 * offset 40: seg_len_cm   i32   4 bytes
 * offset 44: line_a       i32   4 bytes
 * offset 48: line_b       i32   4 bytes
 *
 * Stop layout (12 bytes):
 * offset  0: progress_cm        u32   4 bytes
 * offset  4: corridor_start_cm  u32   4 bytes
 * offset  8: corridor_end_cm    u32   4 bytes
 *
 * File layout (v8 format):
 * - Header (28 bytes):
 *   - MAGIC: u32 (0x42555341 = "BUSA")
 *   - VERSION: u16 (1)
 *   - node_count: u16
 *   - stop_count: u8
 *   - padding: u8[3] (for 4-byte alignment)
 *   - x0_cm: i32
 *   - y0_cm: i32
 *   - lat_avg_deg: f64 (average latitude for projection)
 * - Nodes array: node_count × 52 bytes
 * - Stops array: stop_count × 12 bytes
 * - Grid data (cols, rows, grid_size_cm, offsets, cells)
 * - LUTs: 256 bytes (gaussian) + 128 bytes (logistic)
 * - CRC32: u32 = 4 bytes
 */

import { projectCmToLatLon } from '$lib/parsers/projection';
import type { RouteData, RouteNode, Stop, GridOrigin } from '$lib/types';

const ROUTE_NODE_SIZE = 52;
const STOP_SIZE = 12;
const HEADER_SIZE_V8 = 28; // + lat_avg_deg(8) for total of 28 bytes
const MAGIC = 0x42555341; // "BUSA" in little-endian
const VERSION = 1;

/**
 * Read i64 from DataView (little-endian)
 * Returns BigInt because JavaScript Number can't hold all i64 values
 */
function readI64(dataView: DataView, offset: number): bigint {
	const low = dataView.getUint32(offset, true);
	const high = dataView.getInt32(offset + 4, true);
	// Combine to BigInt: high << 32 | low
	return (BigInt(high) << 32n) | BigInt(low);
}

/**
 * Parse RouteNode from binary data
 */
function parseRouteNode(dataView: DataView, offset: number): RouteNode {
	return {
		len2_cm2: readI64(dataView, offset),
		line_c: readI64(dataView, offset + 8),
		heading_cdeg: dataView.getInt16(offset + 16, true),
		_pad: dataView.getInt16(offset + 18, true),
		x_cm: dataView.getInt32(offset + 20, true),
		y_cm: dataView.getInt32(offset + 24, true),
		cum_dist_cm: dataView.getInt32(offset + 28, true),
		dx_cm: dataView.getInt32(offset + 32, true),
		dy_cm: dataView.getInt32(offset + 36, true),
		seg_len_cm: dataView.getInt32(offset + 40, true),
		line_a: dataView.getInt32(offset + 44, true),
		line_b: dataView.getInt32(offset + 48, true)
	};
}

/**
 * Parse Stop from binary data
 */
function parseStop(dataView: DataView, offset: number): Stop {
	return {
		progress_cm: dataView.getUint32(offset, true),  // u32 in v8 format
		corridor_start_cm: dataView.getUint32(offset + 4, true),
		corridor_end_cm: dataView.getUint32(offset + 8, true)
	};
}

/**
 * Parse route_data.bin file from ArrayBuffer (v8 format)
 *
 * @param buffer - ArrayBuffer containing binary file data
 * @returns Parsed RouteData
 * @throws Error if file format is invalid
 */
export function parseRouteData(buffer: ArrayBuffer): RouteData {
	const dataView = new DataView(buffer);

	if (buffer.byteLength < HEADER_SIZE_V8) {
		throw new Error('File too small to be valid route_data.bin');
	}

	// Read v8 header
	let offset = 0;

	// Read and verify magic bytes
	const magic = dataView.getUint32(offset, true);
	offset += 4;
	if (magic !== MAGIC) {
		throw new Error(`Invalid magic bytes: expected 0x${MAGIC.toString(16)}, got 0x${magic.toString(16)}`);
	}

	// Read and verify version
	const version = dataView.getUint16(offset, true);
	offset += 2;
	if (version !== VERSION) {
		throw new Error(`Unsupported version: ${version}, expected ${VERSION}`);
	}

	// Read node count (u16)
	const node_count = dataView.getUint16(offset, true);
	offset += 2;

	// Read stop count (u8)
	const stop_count = dataView.getUint8(offset);
	offset += 1;

	// Skip 3 padding bytes for alignment
	offset += 3;

	// Read origin coordinates
	const x0_cm = dataView.getInt32(offset, true);
	offset += 4;
	const y0_cm = dataView.getInt32(offset, true);
	offset += 4;

	// Read average latitude for projection (f64 / little-endian)
	const lat_avg_deg_bytes = new DataView(new ArrayBuffer(8));
	for (let i = 0; i < 8; i++) {
		lat_avg_deg_bytes.setUint8(i, dataView.getUint8(offset + i));
	}
	const lat_avg_deg = dataView.getFloat64(offset, true);
	offset += 8;

	// Parse grid origin
	const grid_origin: GridOrigin = { x0_cm, y0_cm };

	// Parse nodes
	const nodes: RouteNode[] = [];
	for (let i = 0; i < node_count; i++) {
		nodes.push(parseRouteNode(dataView, offset));
		offset += ROUTE_NODE_SIZE;
	}

	// Parse stops
	const stops: Stop[] = [];
	for (let i = 0; i < stop_count; i++) {
		stops.push(parseStop(dataView, offset));
		offset += STOP_SIZE;
	}

	// Note: The v8 format has additional data after stops (grid, LUTs, CRC32)
	// but we don't need to parse it for visualization

	return {
		node_count,
		stop_count,
		grid_origin,
		lat_avg_deg,
		nodes,
		stops,
		crc32: 0 // Not parsed in v8 format
	};
}

/**
 * Load and parse a route_data.bin file from a URL or File
 *
 * @param file - File object or URL to fetch
 * @returns Promise resolving to parsed route data
 */
export async function loadRouteData(file: File | string): Promise<RouteData> {
	let buffer: ArrayBuffer;

	if (typeof file === 'string') {
		// Fetch from URL
		const response = await fetch(file);
		if (!response.ok) {
			throw new Error(`Failed to load route data: ${response.statusText}`);
		}
		buffer = await response.arrayBuffer();
	} else {
		// Read from File object
		buffer = await file.arrayBuffer();
	}

	return parseRouteData(buffer);
}

/**
 * Get route geometry for MapLibre GL JS
 *
 * Converts nodes to GeoJSON LineString coordinates
 * Note: This requires inverse projection to get lat/lon
 *
 * @param routeData - Parsed route data
 * @param projectCmToLatLon - Function to convert cm to lat/lon
 * @returns GeoJSON LineString coordinates
 */
export function getRouteGeometry(
	routeData: RouteData,
	projectCmToLatLon: (x_cm: number, y_cm: number, lat_avg_deg: number) => [number, number]
): number[][] {
	return routeData.nodes.map((node) => {
		// Nodes are stored as absolute coordinates (from fixed origin 120E, 20N)
		// grid_origin is just the minimum for spatial indexing, don't add it!
		const [lat, lon] = projectCmToLatLon(node.x_cm, node.y_cm, routeData.lat_avg_deg);
		return [lon, lat]; // GeoJSON uses [lon, lat] order
	});
}

/**
 * Get interpolated bus position and heading based on route progress
 * 
 * @param progress_cm - Bus progress along route in cm
 * @param routeData - Parsed route data
 * @returns Object with interpolated x_cm, y_cm, and heading_cdeg
 */
export function getInterpolatedBusState(
	progress_cm: number,
	routeData: RouteData
): { x_cm: number; y_cm: number; heading_cdeg: number } {
	const nodes = routeData.nodes;
	if (nodes.length === 0) return { x_cm: 0, y_cm: 0, heading_cdeg: 0 };

	// Find the segment containing the progress_cm
	let left = 0;
	let right = nodes.length - 1;

	while (left < right) {
		const mid = Math.floor((left + right + 1) / 2);
		if (nodes[mid].cum_dist_cm <= progress_cm) {
			left = mid;
		} else {
			right = mid - 1;
		}
	}

	const startNode = nodes[left];
	if (left === nodes.length - 1) {
		return { x_cm: startNode.x_cm, y_cm: startNode.y_cm, heading_cdeg: startNode.heading_cdeg };
	}

	const endNode = nodes[left + 1];
	const seg_len = endNode.cum_dist_cm - startNode.cum_dist_cm;

	if (seg_len <= 0) {
		return { x_cm: startNode.x_cm, y_cm: startNode.y_cm, heading_cdeg: startNode.heading_cdeg };
	}

	const t = (progress_cm - startNode.cum_dist_cm) / seg_len;
	const x_cm = startNode.x_cm + t * (endNode.x_cm - startNode.x_cm);
	const y_cm = startNode.y_cm + t * (endNode.y_cm - startNode.y_cm);

	return { x_cm, y_cm, heading_cdeg: startNode.heading_cdeg };
}

/**
 * Get stop positions for MapLibre GL JS
 *
 * Converts stops to GeoJSON Point coordinates
 *
 * @param routeData - Parsed route data
 * @param projectCmToLatLon - Function to convert cm to lat/lon
 * @returns Array of [lon, lat] coordinates
 */
export function getStopPositions(
	routeData: RouteData,
	projectCmToLatLon: (x_cm: number, y_cm: number, lat_avg_deg: number) => [number, number]
): Array<{ index: number; lon: number; lat: number; progress_cm: number }> {
	// We need to interpolate stop positions from the route nodes
	// For now, return the stop progress_cm and approximate position from nearest node
	return routeData.stops.map((stop, index) => {
		// Find the nearest route node
		let minDist = Infinity;
		let nearestNode = routeData.nodes[0];

		for (const node of routeData.nodes) {
			const dist = Math.abs(node.cum_dist_cm - stop.progress_cm);
			if (dist < minDist) {
				minDist = dist;
				nearestNode = node;
			}
		}

		// Nodes are stored as absolute coordinates
		const [lat, lon] = projectCmToLatLon(nearestNode.x_cm, nearestNode.y_cm, routeData.lat_avg_deg);
		return { index, lon, lat, progress_cm: stop.progress_cm };
	});
}

/**
 * Get interpolated lat/lon for a stop by progress_cm
 *
 * Finds the route segment containing the stop and interpolates
 * the position along that segment.
 *
 * @param stopProgressCm - Stop's progress_cm value
 * @param routeData - Parsed route data
 * @returns [lat, lon] or null if stop cannot be interpolated
 */
export function getStopLatLon(
	stopProgressCm: number,
	routeData: RouteData
): [number, number] | null {
	const nodes = routeData.nodes;
	if (nodes.length < 2) return null;

	// Find the segment containing this stop
	for (let i = 0; i < routeData.nodes.length - 1; i++) {
		const node = routeData.nodes[i];
		const nextNode = routeData.nodes[i + 1];

		if (stopProgressCm >= node.cum_dist_cm && stopProgressCm <= nextNode.cum_dist_cm) {
			// Interpolate between nodes
			const seg_len = nextNode.cum_dist_cm - node.cum_dist_cm;
			if (seg_len <= 0) {
				// Fallback to start node
				const [lat, lon] = projectCmToLatLonFromOrigin(node.x_cm, node.y_cm, routeData);
				return [lat, lon];
			}

			const t = (stopProgressCm - node.cum_dist_cm) / seg_len;
			const x_cm = node.x_cm + t * (nextNode.x_cm - node.x_cm);
			const y_cm = node.y_cm + t * (nextNode.y_cm - node.y_cm);

			// Project to lat/lon
			return projectCmToLatLonFromOrigin(x_cm, y_cm, routeData);
		}
	}

	return null;
}

/**
 * Helper to project cm to lat/lon using route data's grid_origin and lat_avg_deg
 * This is needed because projectCmToLatLon doesn't take grid_origin parameter
 */
function projectCmToLatLonFromOrigin(
	x_cm: number,
	y_cm: number,
	routeData: RouteData
): [number, number] {
	// projectCmToLatLon expects coordinates relative to fixed origin (120E, 20N)
	// Nodes are already stored as absolute coordinates, so we pass them directly
	return projectCmToLatLon(x_cm, y_cm, routeData.lat_avg_deg);
}
