/**
 * Binary route data parser
 *
 * Parses route_data.bin files generated by preprocessor.
 * Binary format must match Rust RouteData struct.
 *
 * RouteNode layout (#[repr(C, packed)], 52 bytes):
 * offset  0: len2_cm2     i64   8 bytes
 * offset  8: line_c       i64   8 bytes
 * offset 16: heading_cdeg i16   2 bytes
 * offset 18: _pad         i16   2 bytes
 * offset 20: x_cm         i32   4 bytes
 * offset 24: y_cm         i32   4 bytes
 * offset 28: cum_dist_cm  i32   4 bytes
 * offset 32: dx_cm        i32   4 bytes
 * offset 36: dy_cm        i32   4 bytes
 * offset 40: seg_len_cm   i32   4 bytes
 * offset 44: line_a       i32   4 bytes
 * offset 48: line_b       i32   4 bytes
 *
 * Stop layout (12 bytes):
 * offset  0: progress_cm        i32   4 bytes
 * offset  4: corridor_start_cm  i32   4 bytes
 * offset  8: corridor_end_cm    i32   4 bytes
 *
 * File layout:
 * - Header: node_count (u32), stop_count (u32), x0_cm (i32), y0_cm (i32) = 16 bytes
 * - Nodes array: node_count × 52 bytes
 * - Stops array: stop_count × 12 bytes
 * - CRC32: u32 = 4 bytes
 */

import type { RouteData, RouteNode, Stop, GridOrigin } from '$lib/types';

const ROUTE_NODE_SIZE = 52;
const STOP_SIZE = 12;
const HEADER_SIZE = 16;

/**
 * Read i64 from DataView (little-endian)
 * Returns BigInt because JavaScript Number can't hold all i64 values
 */
function readI64(dataView: DataView, offset: number): bigint {
	const low = dataView.getUint32(offset, true);
	const high = dataView.getInt32(offset + 4, true);
	// Combine to BigInt: high << 32 | low
	return (BigInt(high) << 32n) | BigInt(low);
}

/**
 * Parse RouteNode from binary data
 */
function parseRouteNode(dataView: DataView, offset: number): RouteNode {
	return {
		len2_cm2: readI64(dataView, offset),
		line_c: readI64(dataView, offset + 8),
		heading_cdeg: dataView.getInt16(offset + 16, true),
		_pad: dataView.getInt16(offset + 18, true),
		x_cm: dataView.getInt32(offset + 20, true),
		y_cm: dataView.getInt32(offset + 24, true),
		cum_dist_cm: dataView.getInt32(offset + 28, true),
		dx_cm: dataView.getInt32(offset + 32, true),
		dy_cm: dataView.getInt32(offset + 36, true),
		seg_len_cm: dataView.getInt32(offset + 40, true),
		line_a: dataView.getInt32(offset + 44, true),
		line_b: dataView.getInt32(offset + 48, true)
	};
}

/**
 * Parse Stop from binary data
 */
function parseStop(dataView: DataView, offset: number): Stop {
	return {
		progress_cm: dataView.getInt32(offset, true),
		corridor_start_cm: dataView.getInt32(offset + 4, true),
		corridor_end_cm: dataView.getInt32(offset + 8, true)
	};
}

/**
 * Parse route_data.bin file from ArrayBuffer
 *
 * @param buffer - ArrayBuffer containing binary file data
 * @returns Parsed RouteData
 * @throws Error if file format is invalid
 */
export function parseRouteData(buffer: ArrayBuffer): RouteData {
	const dataView = new DataView(buffer);

	if (buffer.byteLength < HEADER_SIZE) {
		throw new Error('File too small to be valid route_data.bin');
	}

	// Read header
	let offset = 0;
	const node_count = dataView.getUint32(offset, true);
	offset += 4;
	const stop_count = dataView.getUint32(offset, true);
	offset += 4;
	const x0_cm = dataView.getInt32(offset, true);
	offset += 4;
	const y0_cm = dataView.getInt32(offset, true);
	offset += 4;

	// Validate file size
	const expectedSize =
		HEADER_SIZE + node_count * ROUTE_NODE_SIZE + stop_count * STOP_SIZE + 4; // +4 for CRC32
	if (buffer.byteLength !== expectedSize) {
		throw new Error(
			`File size mismatch: expected ${expectedSize} bytes, got ${buffer.byteLength} bytes`
		);
	}

	// Parse grid origin
	const grid_origin: GridOrigin = { x0_cm, y0_cm };

	// Parse nodes
	const nodes: RouteNode[] = [];
	for (let i = 0; i < node_count; i++) {
		nodes.push(parseRouteNode(dataView, offset));
		offset += ROUTE_NODE_SIZE;
	}

	// Parse stops
	const stops: Stop[] = [];
	for (let i = 0; i < stop_count; i++) {
		stops.push(parseStop(dataView, offset));
		offset += STOP_SIZE;
	}

	// Read CRC32
	const crc32 = dataView.getUint32(offset, true);

	return {
		node_count,
		stop_count,
		grid_origin,
		nodes,
		stops,
		crc32
	};
}

/**
 * Load and parse a route_data.bin file from a URL or File
 *
 * @param file - File object or URL to fetch
 * @returns Promise resolving to parsed route data
 */
export async function loadRouteData(file: File | string): Promise<RouteData> {
	let buffer: ArrayBuffer;

	if (typeof file === 'string') {
		// Fetch from URL
		const response = await fetch(file);
		if (!response.ok) {
			throw new Error(`Failed to load route data: ${response.statusText}`);
		}
		buffer = await response.arrayBuffer();
	} else {
		// Read from File object
		buffer = await file.arrayBuffer();
	}

	return parseRouteData(buffer);
}

/**
 * Get route geometry for MapLibre GL JS
 *
 * Converts nodes to GeoJSON LineString coordinates
 * Note: This requires inverse projection to get lat/lon
 *
 * @param routeData - Parsed route data
 * @param projectCmToLatLon - Function to convert cm to lat/lon
 * @returns GeoJSON LineString coordinates
 */
export function getRouteGeometry(
	routeData: RouteData,
	projectCmToLatLon: (x_cm: number, y_cm: number) => [number, number]
): number[][] {
	return routeData.nodes.map((node) => {
		const [lat, lon] = projectCmToLatLon(node.x_cm, node.y_cm);
		return [lon, lat]; // GeoJSON uses [lon, lat] order
	});
}

/**
 * Get stop positions for MapLibre GL JS
 *
 * Converts stops to GeoJSON Point coordinates
 *
 * @param routeData - Parsed route data
 * @param projectCmToLatLon - Function to convert cm to lat/lon
 * @returns Array of [lon, lat] coordinates
 */
export function getStopPositions(
	routeData: RouteData,
	projectCmToLatLon: (x_cm: number, y_cm: number) => [number, number]
): Array<{ index: number; lon: number; lat: number; progress_cm: number }> {
	// We need to interpolate stop positions from the route nodes
	// For now, return the stop progress_cm and approximate position from nearest node
	return routeData.stops.map((stop, index) => {
		// Find the nearest route node
		let minDist = Infinity;
		let nearestNode = routeData.nodes[0];

		for (const node of routeData.nodes) {
			const dist = Math.abs(node.cum_dist_cm - stop.progress_cm);
			if (dist < minDist) {
				minDist = dist;
				nearestNode = node;
			}
		}

		const [lat, lon] = projectCmToLatLon(nearestNode.x_cm, nearestNode.y_cm);
		return { index, lon, lat, progress_cm: stop.progress_cm };
	});
}
