/**
 * Trace JSONL parser
 *
 * Parses trace.jsonl files generated by arrival_detector --trace flag
 * Format: one JSON object per line (JSONL)
 */

import type { TraceRecord, TraceData } from '$lib/types';

/**
 * Parse a trace.jsonl file content
 *
 * @param content - Raw file content (one JSON per line)
 * @returns Array of trace records
 * @throws Error if JSON parsing fails
 */
export function parseTraceJsonl(content: string): TraceData {
	const lines = content.split('\n').filter((line) => line.trim() !== '');

	const records: TraceRecord[] = [];

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i].trim();
		if (!line) continue;

		try {
			const record = JSON.parse(line) as TraceRecord;

			// Validate required fields
			if (typeof record.time !== 'number') {
				throw new Error(`Line ${i + 1}: missing or invalid 'time' field`);
			}
			if (typeof record.s_cm !== 'number') {
				throw new Error(`Line ${i + 1}: missing or invalid 's_cm' field`);
			}
			if (typeof record.v_cms !== 'number') {
				throw new Error(`Line ${i + 1}: missing or invalid 'v_cms' field`);
			}
			if (!Array.isArray(record.active_stops)) {
				throw new Error(`Line ${i + 1}: missing or invalid 'active_stops' field`);
			}
			if (!Array.isArray(record.stop_states)) {
				throw new Error(`Line ${i + 1}: missing or invalid 'stop_states' field`);
			}
			if (typeof record.gps_jump !== 'boolean') {
				throw new Error(`Line ${i + 1}: missing or invalid 'gps_jump' field`);
			}

			records.push(record);
		} catch (e) {
			if (e instanceof SyntaxError) {
				throw new Error(`Line ${i + 1}: invalid JSON - ${e.message}`);
			}
			throw e;
		}
	}

	return records;
}

/**
 * Load and parse a trace.jsonl file from a URL or File
 *
 * @param file - File object or URL to fetch
 * @returns Promise resolving to parsed trace data
 */
export async function loadTraceFile(file: File | string): Promise<TraceData> {
	let content: string;

	if (typeof file === 'string') {
		// Fetch from URL
		const response = await fetch(file);
		if (!response.ok) {
			throw new Error(`Failed to load trace file: ${response.statusText}`);
		}
		content = await response.text();
	} else {
		// Read from File object
		content = await file.text();
	}

	return parseTraceJsonl(content);
}

/**
 * Get time range from trace data
 *
 * @param data - Trace data array
 * @returns [min_time, max_time] in seconds since epoch
 */
export function getTraceTimeRange(data: TraceData): [number, number] {
	if (data.length === 0) return [0, 0];

	let minTime = data[0].time;
	let maxTime = data[0].time;

	for (const record of data) {
		if (record.time < minTime) minTime = record.time;
		if (record.time > maxTime) maxTime = record.time;
	}

	return [minTime, maxTime];
}

/**
 * Filter trace records by time range
 *
 * @param data - Trace data array
 * @param startTime - Start time (seconds since epoch)
 * @param endTime - End time (seconds since epoch)
 * @returns Filtered trace data
 */
export function filterTraceByTime(data: TraceData, startTime: number, endTime: number): TraceData {
	return data.filter((record) => record.time >= startTime && record.time <= endTime);
}

/**
 * Get all unique stop indices from trace data
 *
 * @param data - Trace data array
 * @returns Sorted array of unique stop indices
 */
export function getUniqueStopIndices(data: TraceData): number[] {
	const stops = new Set<number>();

	for (const record of data) {
		for (const stopIdx of record.active_stops) {
			stops.add(stopIdx);
		}
	}

	return Array.from(stops).sort((a, b) => a - b);
}
