//! # Probability Computation Engine
//!
//! This crate provides cached probability computation for bus arrival detection.
//! It wraps the detection probability module with a caching layer to avoid
//! recalculating probabilities for the same timestamp/inputs (e.g., in get_trace_info).
//!
//! ## Features
//!
//! - **Caching**: Avoids recomputing probabilities for identical inputs
//! - **no_std compatible**: Works in embedded environments
//! - **Feature scores**: Exposes intermediate feature calculations
//!
//! ## Usage
//!
//! ```rust
//! use pipeline_probability::ProbabilityEngine;
//! use shared::{PositionSignals, SpeedCms, Stop};
//! use detection::probability::GpsStatus;
//!
//! let mut engine = ProbabilityEngine::new();
//! let signals = PositionSignals::new(100, 100);
//! let stop = Stop {
//!     progress_cm: 1000,
//!     corridor_start_cm: 900,
//!     corridor_end_cm: 1100,
//! };
//!
//! let result = engine.compute(
//!     0,  // timestamp
//!     signals,
//!     50,  // v_cms
//!     &stop,
//!     0,  // dwell_time_s
//!     GpsStatus::Valid,
//! );
//! ```

#![no_std]

use shared::{SpeedCms, PositionSignals, Stop};
use detection::probability::{self, GpsStatus};

// Embedded LUTs for no_std compatibility
// Auto-generated by gen_luts - do not edit manually
const GAUSSIAN_LUT: [u8; 256] = [255, 255, 255, 255, 255, 254, 254, 253, 253, 252, 252, 251, 251, 250, 249, 248, 247, 246, 245, 244, 243, 242, 240, 239, 238, 236, 235, 233, 232, 230, 228, 227, 225, 223, 221, 220, 218, 216, 214, 212, 210, 208, 206, 203, 201, 199, 197, 195, 192, 190, 188, 186, 183, 181, 179, 176, 174, 172, 169, 167, 164, 162, 159, 157, 155, 152, 150, 147, 145, 143, 140, 138, 135, 133, 131, 128, 126, 124, 121, 119, 117, 114, 112, 110, 108, 106, 103, 101, 99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 72, 70, 68, 66, 65, 63, 61, 60, 58, 57, 55, 54, 52, 51, 49, 48, 47, 45, 44, 43, 41, 40, 39, 38, 37, 36, 35, 33, 32, 31, 30, 29, 28, 28, 27, 26, 25, 24, 23, 23, 22, 21, 20, 20, 19, 18, 18, 17, 16, 16, 15, 15, 14, 14, 13, 13, 12, 12, 11, 11, 10, 10, 10, 9, 9, 8, 8, 8, 7, 7, 7, 7, 6, 6, 6, 6, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

const LOGISTIC_LUT: [u8; 128] = [225, 222, 219, 216, 212, 208, 205, 200, 196, 191, 186, 181, 176, 170, 165, 159, 153, 146, 140, 134, 128, 121, 115, 109, 102, 96, 90, 85, 79, 74, 69, 64, 59, 55, 50, 47, 43, 39, 36, 33, 30, 28, 25, 23, 21, 19, 18, 16, 15, 13, 12, 11, 10, 9, 8, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

/// Cached probability computation result
#[derive(Debug, Clone)]
pub struct ProbabilityResult {
    pub probability: u8,
    #[cfg(feature = "std")]
    pub features: detection::trace::FeatureScores,
}

/// Probability computation engine with caching
///
/// Caches the last computation by (timestamp, inputs) to avoid
/// recomputing when get_trace_info() needs the same data.
/// Also stores LUTs internally for no_std compatibility.
pub struct ProbabilityEngine {
    last_result: Option<(u64, ProbabilityResult)>,
    gaussian_lut: [u8; 256],
    logistic_lut: [u8; 128],
}

impl ProbabilityEngine {
    pub fn new() -> Self {
        Self {
            last_result: None,
            gaussian_lut: GAUSSIAN_LUT,
            logistic_lut: LOGISTIC_LUT,
        }
    }

    /// Compute arrival probability (cached)
    ///
    /// Returns cached result if timestamp matches, otherwise computes
    /// new probability and caches it.
    pub fn compute(
        &mut self,
        timestamp: u64,
        signals: PositionSignals,
        v_cms: SpeedCms,
        stop: &Stop,
        dwell_time_s: u16,
        gps_status: GpsStatus,
    ) -> &ProbabilityResult {
        // Check cache
        if let Some((cached_ts, _)) = self.last_result {
            if cached_ts == timestamp {
                // Return cached result (same timestamp = same inputs)
                return &self.last_result.as_ref().unwrap().1;
            }
        }

        // Compute new probability
        let probability = probability::compute_arrival_probability(
            signals,
            v_cms,
            stop,
            dwell_time_s,
            gps_status,
            &self.gaussian_lut,
            &self.logistic_lut,
        );

        #[cfg(feature = "std")]
        let features = probability::compute_feature_scores(
            signals,
            v_cms,
            stop,
            dwell_time_s,
            &self.gaussian_lut,
            &self.logistic_lut,
        );

        #[cfg(feature = "std")]
        let result = ProbabilityResult { probability, features };
        #[cfg(not(feature = "std"))]
        let result = ProbabilityResult { probability };

        self.last_result = Some((timestamp, result));
        &self.last_result.as_ref().unwrap().1
    }

    /// Clear the cache (e.g., on new GPS record)
    pub fn clear(&mut self) {
        self.last_result = None;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use shared::Stop;

    fn mock_stop() -> Stop {
        Stop {
            progress_cm: 1000,
            corridor_start_cm: 900,
            corridor_end_cm: 1100,
        }
    }

    #[test]
    fn test_probability_caching() {
        let mut engine = ProbabilityEngine::new();
        let signals = PositionSignals::new(100, 100);
        let stop = mock_stop();

        // First call computes and caches
        let r1_ptr = {
            let r1 = engine.compute(0, signals, 50, &stop, 0, GpsStatus::Valid);
            r1 as *const ProbabilityResult
        };

        // Second call with same timestamp should return cached result
        let r2 = engine.compute(0, signals, 50, &stop, 0, GpsStatus::Valid);

        // Same reference (cached)
        assert_eq!(r1_ptr, r2 as *const ProbabilityResult);
    }

    #[test]
    fn test_probability_cache_miss() {
        let mut engine = ProbabilityEngine::new();
        let signals = PositionSignals::new(100, 100);
        let stop = mock_stop();

        // First call with timestamp 0
        {
            let _r1 = engine.compute(0, signals, 50, &stop, 0, GpsStatus::Valid);
        }

        // Second call with different timestamp should compute new result
        let r2_ptr = {
            let r2 = engine.compute(1, signals, 50, &stop, 0, GpsStatus::Valid);
            r2 as *const ProbabilityResult
        };

        // Third call with timestamp 1 should return cached result
        let r3 = engine.compute(1, signals, 50, &stop, 0, GpsStatus::Valid);

        // Same reference (cached for timestamp 1)
        assert_eq!(r2_ptr, r3 as *const ProbabilityResult);
    }

    #[test]
    fn test_probability_clear() {
        let mut engine = ProbabilityEngine::new();
        let signals = PositionSignals::new(100, 100);
        let stop = mock_stop();

        // First call
        {
            let _r1 = engine.compute(0, signals, 50, &stop, 0, GpsStatus::Valid);
        }

        // Clear cache
        engine.clear();

        // Second call with same timestamp should compute new result
        let r2_ptr = {
            let r2 = engine.compute(0, signals, 50, &stop, 0, GpsStatus::Valid);
            r2 as *const ProbabilityResult
        };

        // Third call with same timestamp should return cached result
        let r3 = engine.compute(0, signals, 50, &stop, 0, GpsStatus::Valid);

        // Same reference (cached after clear)
        assert_eq!(r2_ptr, r3 as *const ProbabilityResult);
    }
}
