// TZ 23 stops (both directions)
// Generated by get_bus_stops
// Date: 2026-03-07T17:25:53.299Z

window.stopsData = {
  "loc": [
    {
      "lat": 24.196253,
      "lon": 120.655793
    },
    {
      "lat": 24.192885,
      "lon": 120.655391
    },
    {
      "lat": 24.192406,
      "lon": 120.660173
    },
    {
      "lat": 24.19054,
      "lon": 120.661355
    },
    {
      "lat": 24.188333,
      "lon": 120.66271
    },
    {
      "lat": 24.186638,
      "lon": 120.663442
    },
    {
      "lat": 24.184776,
      "lon": 120.664758
    },
    {
      "lat": 24.182972,
      "lon": 120.665698
    },
    {
      "lat": 24.180943,
      "lon": 120.666776
    },
    {
      "lat": 24.178653,
      "lon": 120.668445
    },
    {
      "lat": 24.177472,
      "lon": 120.669374
    },
    {
      "lat": 24.176342,
      "lon": 120.67018
    },
    {
      "lat": 24.175399,
      "lon": 120.670944
    },
    {
      "lat": 24.173843,
      "lon": 120.670852
    },
    {
      "lat": 24.173607,
      "lon": 120.669242
    },
    {
      "lat": 24.173159,
      "lon": 120.666497
    },
    {
      "lat": 24.17254833,
      "lon": 120.6638283
    },
    {
      "lat": 24.17199167,
      "lon": 120.6621617
    },
    {
      "lat": 24.171,
      "lon": 120.658655
    },
    {
      "lat": 24.169455,
      "lon": 120.6558133
    },
    {
      "lat": 24.16734333,
      "lon": 120.653295
    },
    {
      "lat": 24.1656666666667,
      "lon": 120.651643333333
    },
    {
      "lat": 24.16225,
      "lon": 120.65027
    },
    {
      "lat": 24.1588533333333,
      "lon": 120.651903333333
    },
    {
      "lat": 24.156755,
      "lon": 120.650397
    },
    {
      "lat": 24.15439,
      "lon": 120.64996
    },
    {
      "lat": 24.150805,
      "lon": 120.652576666667
    },
    {
      "lat": 24.1508766666667,
      "lon": 120.65567
    },
    {
      "lat": 24.1509166666667,
      "lon": 120.657756666667
    },
    {
      "lat": 24.1508983333333,
      "lon": 120.659933333333
    },
    {
      "lat": 24.1504416666667,
      "lon": 120.661673333333
    },
    {
      "lat": 24.1480516666667,
      "lon": 120.661671666667
    },
    {
      "lat": 24.14645,
      "lon": 120.66167
    },
    {
      "lat": 24.1430266666667,
      "lon": 120.66174
    },
    {
      "lat": 24.1396133333333,
      "lon": 120.6616
    },
    {
      "lat": 24.13708,
      "lon": 120.661726666667
    },
    {
      "lat": 24.1338790042,
      "lon": 120.661699176
    },
    {
      "lat": 24.1321183333333,
      "lon": 120.66205
    },
    {
      "lat": 24.132152,
      "lon": 120.664803
    },
    {
      "lat": 24.130227,
      "lon": 120.668063
    },
    {
      "lat": 24.12787,
      "lon": 120.66931
    },
    {
      "lat": 24.1244033333333,
      "lon": 120.670031666667
    },
    {
      "lat": 24.1223116666667,
      "lon": 120.6708
    },
    {
      "lat": 24.124105,
      "lon": 120.67578
    },
    {
      "lat": 24.1213483333333,
      "lon": 120.679248333333
    },
    {
      "lat": 24.117904,
      "lon": 120.679296
    },
    {
      "lat": 24.11585,
      "lon": 120.679183
    },
    {
      "lat": 24.1136294976,
      "lon": 120.678935051
    },
    {
      "lat": 24.10855,
      "lon": 120.679867
    },
    {
      "lat": 24.105317,
      "lon": 120.680867
    },
    {
      "lat": 24.103483,
      "lon": 120.681283
    },
    {
      "lat": 24.101,
      "lon": 120.6822
    },
    {
      "lat": 24.0993314947,
      "lon": 120.679525137
    },
    {
      "lat": 24.095721,
      "lon": 120.679402
    },
    {
      "lat": 24.0957273627,
      "lon": 120.680490732
    },
    {
      "lat": 24.096082,
      "lon": 120.681708
    },
    {
      "lat": 24.0953943671,
      "lon": 120.685291886
    },
    {
      "lat": 24.091483,
      "lon": 120.691717
    },
    {
      "lat": 24.0897,
      "lon": 120.69385
    },
    {
      "lat": 24.087433,
      "lon": 120.695933
    },
    {
      "lat": 24.083617,
      "lon": 120.697133
    },
    {
      "lat": 24.080117,
      "lon": 120.69825
    }
  ],
  "radius": [
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 80,
      "exit": 80
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 110,
      "exit": 110
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    }
  ],
  "orderNo": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62
  ],
  "stopName": [
    "黎明經貿路口",
    "綠美圖(中科路)",
    "貿易三村(中清路)",
    "后庄國宅",
    "中清后庄路口",
    "后庄仔",
    "頂陳平",
    "陳平",
    "全民醫院",
    "大德國中",
    "水湳市場(中清路)",
    "水湳",
    "下水湳",
    "捷運文心中清站(文心路)",
    "文心陝西路口",
    "臺灣日報",
    "重慶國小",
    "文心河南路口",
    "捷運文華高中站(文心路)",
    "文心甘肅路口",
    "捷運文心櫻花站(文心路)",
    "文心青海路口",
    "捷運市政府站(臺灣大道)",
    "大墩十九街口",
    "大墩十八街口",
    "大墩大業路口",
    "公益東興路口",
    "公益精誠路口",
    "公益公園(公益路)",
    "公益中美街口",
    "美村公益路口",
    "美村向上北路口",
    "美村向上路口",
    "向上國中",
    "美術館(美村路)",
    "美村五權五街口",
    "美村五權八街口",
    "南屯美村路口",
    "永安市場",
    "五權車站(五權路)",
    "公共資訊圖書館(五權南路)",
    "五權南永和街口",
    "美村五權南路口",
    "中興大學(興大路)",
    "中興大學(國光路)",
    "國光忠明南路口",
    "國光橋",
    "國光東興路口",
    "大里仁愛醫院(國光路)",
    "國光德芳路口",
    "國光花市",
    "國光大里路口",
    "大新停車場",
    "東里國中路口",
    "市立大里高中(大衛路口)",
    "台電大里服務所",
    "大突寮(國中路)",
    "中興仁化路口",
    "青年高中",
    "大里圖書館(中興路)",
    "草湖",
    "中興東南路口"
  ],
  "stopNameEn": [
    "Liming-Jingmao Intersection",
    "Taichung Green Museumbrary(Zhongke Road)",
    "Maoyi 3rd Village(Zhongqing Road)",
    "Houzhuang Civil House",
    "Zhongqing-Houzhuang Intersection",
    "Houzhuangzi",
    "Dingchenping",
    "Chenping",
    "Quanmin Hospital",
    "Dade Junior High School",
    "Shuinan Market(Zhongqing Road)",
    "Shuinan",
    "Xiashuinan",
    "MRT Wenxin Zhongqing Station(Wenxin Road)",
    "Wenxin-Shanxi Intersection",
    "Taiwan Daily News",
    "Chongqing Elementary School",
    "Wenxin-Henan Intersection",
    "MRT Wenhua Senior High School Station(Wenxin Road)",
    "Wenxin-Gansu Intersection",
    "MRT Wenxin Yinghua Station(Wenxin Road)",
    "Wenxin-Qinghai Intersection",
    "MRT Taichung City Hall Station(Taiwan Boulevard)",
    "Dadun 19th Street",
    "Dadun 18th Street",
    "Dadun-Daye Intersection",
    "Gongyi-Dongxing Intersection",
    "Gongyi-Jingcheng Intersection",
    "Gongyi Park(Gongyi Road)",
    "Gongyi-Zhongmei Intersection",
    "Meicun-Gongyi Intersection",
    "Meicun-Xiangshang N. Intersection",
    "Meicun-Xinngshang Intersection.",
    "Siang Shang Junior High School",
    "National Taiwan Museum of Fine Arts(Meicun Road)",
    "Meicun-Wuquan 5th Intersection",
    "Meicun-Wuquan 8th Intersection",
    "Nantun-Meicun Intersection",
    "Yongan Market",
    "Wuquan Station(Wuquan Road)",
    "National Library of Public Information(Wuquan S. Road)",
    "Wuquan S.-Yonghe Intersection",
    "Meicun-Wuquan S. Intersection",
    "Chung Hsing University(Xingda Road)",
    "Chung Hsing University(Guoguang Road)",
    "Guoguang-Zhongming S. Intersection",
    "Guoguang Bridge",
    "Guoguang-Dongxing Intersection",
    "Dali Ren-Ai Hospital(Guoguang Road)",
    "Guoguang-Defang Intersection",
    "Guoguang Flower Market",
    "Guoguang-Dali Intersection",
    "Daxin Parking Lot",
    "Dongli Guozhong Intersection",
    "Dali S. H. S.(Dawei Intersection)",
    "Taipower Service center(Dali).",
    "Datuliao(Guozhong Road)",
    "Zhongxing-Renhua Intersection",
    "Youth Senior High School",
    "Dali Library(Zhongxing Road)",
    "Caohu",
    "Zhongxing-Dongnan Intersection"
  ],
  "alt": "0",
  "branchCode": "0",
  "goback": "0",
  "hl": "zh-Hans",
  "xno": "23",
  "_siteName": "TZ",
  "_routeName": "23",
  "_routeGoBack": 0
};

window.stopsDataBack = {
  "loc": [
    {
      "lat": 24.080967,
      "lon": 120.698233
    },
    {
      "lat": 24.083467,
      "lon": 120.69745
    },
    {
      "lat": 24.0866333343,
      "lon": 120.696353316
    },
    {
      "lat": 24.0886657122,
      "lon": 120.695355535
    },
    {
      "lat": 24.0898,
      "lon": 120.6941
    },
    {
      "lat": 24.091617,
      "lon": 120.691783
    },
    {
      "lat": 24.0953943671,
      "lon": 120.685291886
    },
    {
      "lat": 24.096082,
      "lon": 120.681708
    },
    {
      "lat": 24.0956490108,
      "lon": 120.680319071
    },
    {
      "lat": 24.095809,
      "lon": 120.679472
    },
    {
      "lat": 24.099354,
      "lon": 120.679459
    },
    {
      "lat": 24.101,
      "lon": 120.6822
    },
    {
      "lat": 24.103483,
      "lon": 120.681283
    },
    {
      "lat": 24.105317,
      "lon": 120.680867
    },
    {
      "lat": 24.10855,
      "lon": 120.679867
    },
    {
      "lat": 24.1136294976,
      "lon": 120.678935051
    },
    {
      "lat": 24.11585,
      "lon": 120.679183
    },
    {
      "lat": 24.1182319396,
      "lon": 120.679417849
    },
    {
      "lat": 24.1213483333333,
      "lon": 120.679248333333
    },
    {
      "lat": 24.124105,
      "lon": 120.67578
    },
    {
      "lat": 24.1223116666667,
      "lon": 120.6708
    },
    {
      "lat": 24.12266167,
      "lon": 120.67
    },
    {
      "lat": 24.1244033333333,
      "lon": 120.670031666667
    },
    {
      "lat": 24.12746333,
      "lon": 120.6697333
    },
    {
      "lat": 24.130149,
      "lon": 120.668283
    },
    {
      "lat": 24.132152,
      "lon": 120.664803
    },
    {
      "lat": 24.1321183333333,
      "lon": 120.66205
    },
    {
      "lat": 24.1338790042,
      "lon": 120.661699176
    },
    {
      "lat": 24.13708,
      "lon": 120.661726666667
    },
    {
      "lat": 24.1396133333333,
      "lon": 120.6616
    },
    {
      "lat": 24.142481,
      "lon": 120.661795
    },
    {
      "lat": 24.14645,
      "lon": 120.66167
    },
    {
      "lat": 24.1480516666667,
      "lon": 120.661671666667
    },
    {
      "lat": 24.1508983333333,
      "lon": 120.659933333333
    },
    {
      "lat": 24.1509166666667,
      "lon": 120.657756666667
    },
    {
      "lat": 24.1508766666667,
      "lon": 120.65567
    },
    {
      "lat": 24.150805,
      "lon": 120.652576666667
    },
    {
      "lat": 24.1511,
      "lon": 120.649832
    },
    {
      "lat": 24.15439,
      "lon": 120.64996
    },
    {
      "lat": 24.15646,
      "lon": 120.65024
    },
    {
      "lat": 24.1588533333333,
      "lon": 120.651903333333
    },
    {
      "lat": 24.16225,
      "lon": 120.65027
    },
    {
      "lat": 24.163775,
      "lon": 120.65057
    },
    {
      "lat": 24.165,
      "lon": 120.651275
    },
    {
      "lat": 24.166905,
      "lon": 120.653
    },
    {
      "lat": 24.167853,
      "lon": 120.654319
    },
    {
      "lat": 24.16961667,
      "lon": 120.656385
    },
    {
      "lat": 24.170977,
      "lon": 120.659358
    },
    {
      "lat": 24.17163,
      "lon": 120.6613283
    },
    {
      "lat": 24.17224333,
      "lon": 120.6633533
    },
    {
      "lat": 24.17283833,
      "lon": 120.66573
    },
    {
      "lat": 24.17322667,
      "lon": 120.668385
    },
    {
      "lat": 24.175399,
      "lon": 120.670944
    },
    {
      "lat": 24.176342,
      "lon": 120.67018
    },
    {
      "lat": 24.177472,
      "lon": 120.669374
    },
    {
      "lat": 24.178653,
      "lon": 120.668445
    },
    {
      "lat": 24.180943,
      "lon": 120.666776
    },
    {
      "lat": 24.182972,
      "lon": 120.665698
    },
    {
      "lat": 24.184776,
      "lon": 120.664758
    },
    {
      "lat": 24.186245,
      "lon": 120.66381
    },
    {
      "lat": 24.188333,
      "lon": 120.66271
    },
    {
      "lat": 24.19054,
      "lon": 120.661355
    },
    {
      "lat": 24.192863,
      "lon": 120.658591
    },
    {
      "lat": 24.192835,
      "lon": 120.655429
    },
    {
      "lat": 24.195534,
      "lon": 120.654586
    }
  ],
  "radius": [
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 30,
      "exit": 30
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 80,
      "exit": 80
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    },
    {
      "entry": 50,
      "exit": 50
    }
  ],
  "orderNo": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65
  ],
  "stopName": [
    "中興東南路口",
    "草湖",
    "財政部印刷廠",
    "大里圖書館(中興路)",
    "青年高中",
    "中興仁化路口",
    "大突寮(國中路)",
    "台電大里服務所",
    "市立大里高中(大衛路口)",
    "東里國中路口",
    "大新停車場",
    "國光大里路口",
    "國光花市",
    "國光德芳路口",
    "大里仁愛醫院(國光路)",
    "國光東興路口",
    "國光橋",
    "國光忠明南路口",
    "中興大學(國光路)",
    "中興大學(興大路)",
    "美村五權南路口",
    "永和社區",
    "五權南永和街口",
    "公共資訊圖書館(五權南路)",
    "五權車站(五權路)",
    "永安市場",
    "南屯美村路口",
    "美村五權八街口",
    "美村五權五街口",
    "美術館(美村路)",
    "向上國中",
    "美村向上路口",
    "美村向上北路口",
    "公益中美街口",
    "公益公園(公益路)",
    "公益精誠路口",
    "公益東興路口",
    "大墩公益路口",
    "大墩大業路口",
    "大墩十八街口",
    "大墩十九街口",
    "捷運市政府站(臺灣大道)",
    "文心四川路口",
    "文心青海路口",
    "文心西屯路口",
    "捷運文心櫻花站(文心路)",
    "文心甘肅路口",
    "捷運文華高中站(文心路)",
    "文心河南路口",
    "重慶國小",
    "臺灣日報",
    "文心陝西路口",
    "下水湳",
    "水湳",
    "水湳市場(中清路)",
    "大德國中",
    "全民醫院",
    "陳平",
    "頂陳平",
    "后庄仔",
    "中清后庄路口",
    "后庄國宅",
    "貿易三村(經貿七路)",
    "綠美圖(中科路)",
    "黎明經貿路口"
  ],
  "stopNameEn": [
    "Zhongxing-Dongnan Intersection",
    "Caohu",
    "The Printing Plant. Ministry of Finance",
    "Dali Library(Zhongxing Road)",
    "Youth Senior High School",
    "Zhongxing-Renhua Intersection",
    "Datuliao(Guozhong Road)",
    "Taipower Service center(Dali).",
    "Dali S. H. S.(Dawei Intersection)",
    "Dongli Guozhong Intersection",
    "Daxin Parking Lot",
    "Guoguang-Dali Intersection",
    "Guoguang Flower Market",
    "Guoguang-Defang Intersection",
    "Dali Ren-Ai Hospital(Guoguang Road)",
    "Guoguang-Dongxing Intersection",
    "Guoguang Bridge",
    "Guoguang-Zhongming S. Intersection",
    "Chung Hsing University(Guoguang Road)",
    "Chung Hsing University(Xingda Road)",
    "Meicun-Wuquan S. Intersection",
    "Yonghe Community",
    "Wuquan S.-Yonghe Intersection",
    "National Library of Public Information(Wuquan S. Road)",
    "Wuquan Station(Wuquan Road)",
    "Yongan Market",
    "Nantun-Meicun Intersection",
    "Meicun-Wuquan 8th Intersection",
    "Meicun-Wuquan 5th Intersection",
    "National Taiwan Museum of Fine Arts(Meicun Road)",
    "Siang Shang Junior High School",
    "Meicun-Xinngshang Intersection.",
    "Meicun-Xiangshang N. Intersection",
    "Gongyi-Zhongmei Intersection",
    "Gongyi Park(Gongyi Road)",
    "Gongyi-Jingcheng Intersection",
    "Gongyi-Dongxing Intersection",
    "Dadun Gongyi Intersection",
    "Dadun-Daye Intersection",
    "Dadun 18th Street",
    "Dadun 19th Street",
    "MRT Taichung City Hall Station(Taiwan Boulevard)",
    "Wenxin-Sichuan Intersection",
    "Wenxin-Qinghai Intersection",
    "Wenxin-Xitun Intersection",
    "MRT Wenxin Yinghua Station(Wenxin Road)",
    "Wenxin-Gansu Intersection",
    "MRT Wenhua Senior High School Station(Wenxin Road)",
    "Wenxin-Henan Intersection",
    "Chongqing Elementary School",
    "Taiwan Daily News",
    "Wenxin-Shanxi Intersection",
    "Xiashuinan",
    "Shuinan",
    "Shuinan Market(Zhongqing Road)",
    "Dade Junior High School",
    "Quanmin Hospital",
    "Chenping",
    "Dingchenping",
    "Houzhuangzi",
    "Zhongqing-Houzhuang Intersection",
    "Houzhuang Civil House",
    "Maoyi 3rd Village(Jingmao 7th Rd.)",
    "Taichung Green Museumbrary(Zhongke Road)",
    "Liming-Jingmao Intersection"
  ],
  "alt": "0",
  "branchCode": "0",
  "goback": "1",
  "hl": "zh-Hans",
  "xno": "23",
  "_siteName": "TZ",
  "_routeName": "23",
  "_routeGoBack": 1
};


